apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: manager-monitor
  namespace: md5-cracker
  labels:
    app: manager
    release: monitoring
spec:
  selector:
    matchLabels:
      app: manager
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics
  - port: http
    interval: 30s
    path: /health