apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-config
  namespace: md5-cracker
data:
  METRICS_PORT: "7077"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: "guest"
  RABBITMQ_PASS: "guest"