apiVersion: v1
kind: ConfigMap
metadata:
  name: manager-config
  namespace: md5-cracker
data:
  TASK_SIZE: "100000"
  MONGO_HOST: "mongodb"
  MONGO_PORT: "27017"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: "guest"
  RABBITMQ_PASS: "guest"