apiVersion: v1
kind: Service
metadata:
  name: manager
  namespace: md5-cracker
  labels:
    app: manager
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 5055
    targetPort: 5055
  - name: metrics
    port: 8088
    targetPort: 8088
  selector:
    app: manager